/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab7_sub;

public class DimSumOrdering
{
    // This stores the dim sum dishes in the system
    static DimSum[] dishes;

    // The constructor of DimSumOrdering
    public DimSumOrdering()
    {
        //
        // Task 2 - Initialize the dim sum dishes in the system
        //
        dishes = new DimSum[4];
        dishes[0] = new DimSum("Barbecued Pork Bun", 25f);
        dishes[1] = new DimSum("Shrimp Dumpling", 38f);
        dishes[2] = new DimSum("Siu Mai", 30f);
        dishes[3] = new DimSum("Spring Roll", 25f);
        
    }
    
    // Start the ordering system
    public static int[] start(int[] inputArray) {
        int i, j;
        int[] result = new int[4];
            
        System.out.println("Welcome to the G/F restaurant!");
        System.out.println();
            
        for (i=0; i<dishes.length; i++) {
                
            System.out.print((i+1) + ") ");
            System.out.print(dishes[i].getName());
            System.out.print(" - $");
            System.out.println(dishes[i].getPrice());   
        }
        System.out.println();

        for (j=0; j<4; j++) {
            dishes[j].order(inputArray[j]);
            result[j] = dishes[j].getQuantity();
        }

        System.out.println();
      
        return result;
    }
    
    
    // Show the order
    public static float showBill(int[] inputArray) {
        System.out.println("----------------------------------");
        
        int j;
        float total = 0;
        for (j=0; j<4; j++) {
            total += inputArray[j]*dishes[j].getPrice();
        }
        System.out.println("Bill Total: $" + total);
        return total;
    }
    
    // The main method to start the program
    public static void main(String[] args) {
        DimSumOrdering ordering = new DimSumOrdering();
        int[] NewOrder = new int[]{1,2,3,4};
        ordering.start(NewOrder);
        ordering.showBill(NewOrder);
    }

}